/**
 * Ethnicity list based on MyHeritage ethnicity wishlist
 * Source: https://www.reddit.com/r/MyHeritage/comments/1e41mrz/ethnicity_wishlist_this_is_the_list_of/
 */
export const ETHNICITY_OPTIONS = [
    { label: 'Prefer not to say', value: 'prefer_not_to_say' },
    { label: 'African', value: 'african' },
    { label: 'African American', value: 'african_american' },
    { label: 'Afrikaner', value: 'afrikaner' },
    { label: 'Albanian', value: 'albanian' },
    { label: 'Algerian', value: 'algerian' },
    { label: 'Arab', value: 'arab' },
    { label: 'Armenian', value: 'armenian' },
    { label: 'Ashkenazi Jewish', value: 'ashkenazi_jewish' },
    { label: 'Asian', value: 'asian' },
    { label: 'Basque', value: 'basque' },
    { label: 'Belarusian', value: 'belarusian' },
    { label: 'Bengali', value: 'bengali' },
    { label: 'Berber', value: 'berber' },
    { label: 'Bosnian', value: 'bosnian' },
    { label: 'Brazilian', value: 'brazilian' },
    { label: 'Bulgarian', value: 'bulgarian' },
    { label: 'Cajun', value: 'cajun' },
    { label: 'Caribbean', value: 'caribbean' },
    { label: 'Central Asian', value: 'central_asian' },
    { label: 'Chinese', value: 'chinese' },
    { label: 'Croatian', value: 'croatian' },
    { label: 'Czech', value: 'czech' },
    { label: 'Danish', value: 'danish' },
    { label: 'Dutch', value: 'dutch' },
    { label: 'East Asian', value: 'east_asian' },
    { label: 'Eastern European', value: 'eastern_european' },
    { label: 'English', value: 'english' },
    { label: 'Estonian', value: 'estonian' },
    { label: 'Filipino', value: 'filipino' },
    { label: 'Finnish', value: 'finnish' },
    { label: 'French', value: 'french' },
    { label: 'German', value: 'german' },
    { label: 'Greek', value: 'greek' },
    { label: 'Gujarati', value: 'gujarati' },
    { label: 'Hispanic', value: 'hispanic' },
    { label: 'Hungarian', value: 'hungarian' },
    { label: 'Iberian', value: 'iberian' },
    { label: 'Indian', value: 'indian' },
    { label: 'Indigenous American', value: 'indigenous_american' },
    { label: 'Indonesian', value: 'indonesian' },
    { label: 'Iranian', value: 'iranian' },
    { label: 'Irish', value: 'irish' },
    { label: 'Italian', value: 'italian' },
    { label: 'Japanese', value: 'japanese' },
    { label: 'Jewish', value: 'jewish' },
    { label: 'Korean', value: 'korean' },
    { label: 'Latvian', value: 'latvian' },
    { label: 'Lithuanian', value: 'lithuanian' },
    { label: 'Macedonian', value: 'macedonian' },
    { label: 'Malay', value: 'malay' },
    { label: 'Mediterranean', value: 'mediterranean' },
    { label: 'Mexican', value: 'mexican' },
    { label: 'Middle Eastern', value: 'middle_eastern' },
    { label: 'Native American', value: 'native_american' },
    { label: 'Nigerian', value: 'nigerian' },
    { label: 'North African', value: 'north_african' },
    { label: 'Norwegian', value: 'norwegian' },
    { label: 'Pakistani', value: 'pakistani' },
    { label: 'Polish', value: 'polish' },
    { label: 'Portuguese', value: 'portuguese' },
    { label: 'Romanian', value: 'romanian' },
    { label: 'Russian', value: 'russian' },
    { label: 'Scandinavian', value: 'scandinavian' },
    { label: 'Scottish', value: 'scottish' },
    { label: 'Serbian', value: 'serbian' },
    { label: 'Sephardic Jewish', value: 'sephardic_jewish' },
    { label: 'Sicilian', value: 'sicilian' },
    { label: 'Slovak', value: 'slovak' },
    { label: 'Slovenian', value: 'slovenian' },
    { label: 'South Asian', value: 'south_asian' },
    { label: 'Southeast Asian', value: 'southeast_asian' },
    { label: 'Spanish', value: 'spanish' },
    { label: 'Swedish', value: 'swedish' },
    { label: 'Swiss', value: 'swiss' },
    { label: 'Thai', value: 'thai' },
    { label: 'Turkish', value: 'turkish' },
    { label: 'Ukrainian', value: 'ukrainian' },
    { label: 'Vietnamese', value: 'vietnamese' },
    { label: 'Welsh', value: 'welsh' },
    { label: 'West Asian', value: 'west_asian' },
    { label: 'Yugoslavian', value: 'yugoslavian' },
];
