/**
 * Health conditions list based on NHS Inform A-Z
 * Source: https://www.nhsinform.scot/illnesses-and-conditions/a-to-z/
 * 
 * Comprehensive list of health conditions from NHS Inform Scotland's A-Z directory.
 * This list is searchable and used in the health conditions input field.
 */
export const HEALTH_CONDITIONS = [
    // A
    'Acne',
    'ADHD (Attention Deficit Hyperactivity Disorder)',
    'AIDS and HIV',
    'Alcohol-related liver disease',
    'Allergies',
    'Alzheimer\'s disease',
    'Anaemia',
    'Angina',
    'Ankylosing spondylitis',
    'Anorexia nervosa',
    'Anxiety',
    'Appendicitis',
    'Arthritis',
    'Asbestosis',
    'Asthma',
    'Atrial fibrillation',
    'Autism',
    'Autoimmune disorders',
    
    // B
    'Back pain',
    'Bacterial vaginosis',
    'Bell\'s palsy',
    'Bipolar disorder',
    'Bladder cancer',
    'Bladder problems',
    'Blood clots',
    'Blood pressure (high)',
    'Blood pressure (low)',
    'Bone cancer',
    'Bone fractures',
    'Bowel cancer',
    'Bowel incontinence',
    'Brain tumours',
    'Breast cancer',
    'Breast conditions',
    'Bronchitis',
    'Bulimia',
    'Bursitis',
    
    // C
    'Cancer',
    'Carpal tunnel syndrome',
    'Cataracts',
    'Cellulitis',
    'Celiac disease',
    'Cervical cancer',
    'Chickenpox',
    'Chlamydia',
    'Chronic fatigue syndrome',
    'Chronic kidney disease',
    'Chronic obstructive pulmonary disease (COPD)',
    'Chronic pain',
    'Cirrhosis',
    'Cold sores',
    'Colon cancer',
    'Common cold',
    'Conjunctivitis',
    'Constipation',
    'Coronary heart disease',
    'Crohn\'s disease',
    'Cystic fibrosis',
    'Cystitis',
    
    // D
    'Dandruff',
    'Deafness',
    'Deep vein thrombosis',
    'Dementia',
    'Dental problems',
    'Depression',
    'Dermatitis',
    'Diabetes (type 1)',
    'Diabetes (type 2)',
    'Diarrhoea',
    'Digestive disorders',
    'Diverticular disease',
    'Down\'s syndrome',
    'Dry eye syndrome',
    'Dyslexia',
    
    // E
    'Ear infections',
    'Earwax build-up',
    'Eating disorders',
    'Eczema',
    'Endometriosis',
    'Epilepsy',
    'Erectile dysfunction',
    'Eye problems',
    
    // F
    'Fibroids',
    'Fibromyalgia',
    'Food poisoning',
    'Fungal nail infection',
    
    // G
    'Gallstones',
    'Gastroenteritis',
    'Gastrointestinal issues',
    'Genital herpes',
    'Genital warts',
    'Glandular fever',
    'Glaucoma',
    'Goitre',
    'Gonorrhoea',
    'Gout',
    'Gum disease',
    
    // H
    'Haemorrhoids (piles)',
    'Hair loss',
    'Hay fever',
    'Headaches',
    'Hearing loss',
    'Heart attack',
    'Heart disease',
    'Heart failure',
    'Hepatitis A',
    'Hepatitis B',
    'Hepatitis C',
    'Hernia',
    'Herpes',
    'Hiatus hernia',
    'High cholesterol',
    'Hormonal imbalances',
    'Huntington\'s disease',
    'Hyperthyroidism',
    'Hypertension',
    'Hypothyroidism',
    
    // I
    'IBS (Irritable Bowel Syndrome)',
    'Impetigo',
    'Incontinence',
    'Indigestion',
    'Infertility',
    'Inflammatory bowel disease',
    'Influenza (flu)',
    'Ingrown toenail',
    'Insomnia',
    'Iron deficiency anaemia',
    
    // J
    'Jaundice',
    'Joint pain',
    
    // K
    'Kidney cancer',
    'Kidney disease',
    'Kidney infection',
    'Kidney stones',
    
    // L
    'Lactose intolerance',
    'Laryngitis',
    'Leukaemia',
    'Liver cancer',
    'Liver disease',
    'Lung cancer',
    'Lupus',
    'Lyme disease',
    'Lymphoma',
    
    // M
    'Macular degeneration',
    'Malaria',
    'Measles',
    'Meningitis',
    'Menopause',
    'Menstrual problems',
    'Mental health conditions',
    'Migraines',
    'Miscarriage',
    'Motor neurone disease',
    'Multiple sclerosis',
    'Mumps',
    'Muscle pain',
    'Myalgic encephalomyelitis (ME)',
    
    // N
    'Narcolepsy',
    'Nasal polyps',
    'Nausea',
    'Nosebleeds',
    'Norovirus',
    
    // O
    'Obesity',
    'Obsessive compulsive disorder (OCD)',
    'Osteoarthritis',
    'Osteoporosis',
    'Ovarian cancer',
    'Overactive thyroid',
    
    // P
    'Pancreatic cancer',
    'Panic disorder',
    'Parkinson\'s disease',
    'PCOS (Polycystic Ovary Syndrome)',
    'Pelvic inflammatory disease',
    'Peptic ulcers',
    'Peripheral neuropathy',
    'Piles (haemorrhoids)',
    'Pink eye',
    'PMS (Premenstrual Syndrome)',
    'Pneumonia',
    'Post-traumatic stress disorder (PTSD)',
    'Pregnancy complications',
    'Prostate cancer',
    'Psoriasis',
    'Psoriatic arthritis',
    'Pulmonary embolism',
    
    // R
    'Raynaud\'s phenomenon',
    'Rectal bleeding',
    'Restless legs syndrome',
    'Rheumatoid arthritis',
    'Ringworm',
    'Rosacea',
    'Rotator cuff injury',
    
    // S
    'Scabies',
    'Scarlet fever',
    'Schizophrenia',
    'Sciatica',
    'Scoliosis',
    'Seasonal affective disorder (SAD)',
    'Shingles',
    'Sinusitis',
    'Skin cancer',
    'Skin conditions',
    'Sleep apnoea',
    'Sleep disorders',
    'Slipped disc',
    'Smoking-related diseases',
    'Sore throat',
    'Spinal stenosis',
    'Stomach cancer',
    'Stomach ulcers',
    'Stroke',
    'Stye',
    
    // T
    'Tendinitis',
    'Testicular cancer',
    'Thrush',
    'Thyroid cancer',
    'Thyroid disorders',
    'Tinnitus',
    'Tonsillitis',
    'Tourette\'s syndrome',
    'Tuberculosis (TB)',
    'Type 1 diabetes',
    'Type 2 diabetes',
    
    // U
    'Ulcerative colitis',
    'Underactive thyroid',
    'Urinary incontinence',
    'Urinary tract infection (UTI)',
    'Uterine fibroids',
    
    // V
    'Varicose veins',
    'Vertigo',
    'Vision problems',
    'Vitiligo',
    'Vomiting',
    
    // W
    'Whooping cough',
    'Worms',
    
    // Y
    'Yellow fever',
    
    // Z
    'Zika virus',
];
