/**
 * Medications list based on NHS UK Medicines A-Z
 * Source: https://www.nhs.uk/medicines/
 * 
 * Comprehensive list of medications from NHS UK's Medicines A-Z directory.
 * This list is searchable and used in the medications input field.
 */
export const MEDICATIONS = [
    // A
    'Abacavir',
    'Abatacept',
    'Abilify (Aripiprazole)',
    'Acamprosate',
    'Acarbose',
    'Acebutolol',
    'Acetazolamide',
    'Aciclovir',
    'Acitretin',
    'Adalimumab',
    'Adapalene',
    'Adrenaline (Epinephrine)',
    'Agomelatine',
    'Albendazole',
    'Albuterol (Salbutamol)',
    'Alclometasone',
    'Aldesleukin',
    'Alemtuzumab',
    'Alendronic acid',
    'Alfentanil',
    'Alfuzosin',
    'Alimemazine',
    'Allopurinol',
    'Alogliptin',
    'Alprazolam',
    'Alprostadil',
    'Altretamine',
    'Aluminium hydroxide',
    'Amantadine',
    'Amifostine',
    'Amikacin',
    'Amiloride',
    'Aminophylline',
    'Amiodarone',
    'Amitriptyline',
    'Amlodipine',
    'Amoxicillin',
    'Amphotericin',
    'Ampicillin',
    'Anagrelide',
    'Anastrozole',
    'Apixaban',
    'Apremilast',
    'Aprepitant',
    'Aripiprazole',
    'Arsenic trioxide',
    'Aspirin',
    'Atazanavir',
    'Atenolol',
    'Atomoxetine',
    'Atorvastatin',
    'Atovaquone',
    'Atracurium',
    'Atropine',
    'Auranofin',
    'Azathioprine',
    'Azelaic acid',
    'Azithromycin',
    'Aztreonam',
    
    // B
    'Baclofen',
    'Balsalazide',
    'Beclometasone',
    'Bedaquiline',
    'Belimumab',
    'Bendroflumethiazide',
    'Benperidol',
    'Benzathine benzylpenicillin',
    'Benzhexol',
    'Benzocaine',
    'Benzodiazepines',
    'Benzoyl peroxide',
    'Benzylpenicillin',
    'Betahistine',
    'Betamethasone',
    'Betaxolol',
    'Bethanechol',
    'Bevacizumab',
    'Bezafibrate',
    'Bicalutamide',
    'Bimatoprost',
    'Bisacodyl',
    'Bisoprolol',
    'Bleomycin',
    'Bortezomib',
    'Bosentan',
    'Brimonidine',
    'Brinzolamide',
    'Bromocriptine',
    'Brompheniramine',
    'Budesonide',
    'Bumetanide',
    'Bupivacaine',
    'Buprenorphine',
    'Bupropion',
    'Buspirone',
    'Busulfan',
    'Butylscopolamine',
    
    // C
    'Cabergoline',
    'Cabozantinib',
    'Caffeine',
    'Calcipotriol',
    'Calcitriol',
    'Calcium carbonate',
    'Calcium supplements',
    'Candesartan',
    'Capecitabine',
    'Capreomycin',
    'Captopril',
    'Carbamazepine',
    'Carbidopa',
    'Carbimazole',
    'Carboplatin',
    'Carvedilol',
    'Caspofungin',
    'Cefaclor',
    'Cefadroxil',
    'Cefalexin',
    'Cefazolin',
    'Cefixime',
    'Cefotaxime',
    'Cefoxitin',
    'Cefpodoxime',
    'Ceftazidime',
    'Ceftriaxone',
    'Cefuroxime',
    'Celecoxib',
    'Celiprolol',
    'Cephalexin',
    'Cetirizine',
    'Cetuximab',
    'Charcoal (activated)',
    'Chlorambucil',
    'Chloramphenicol',
    'Chlordiazepoxide',
    'Chlorhexidine',
    'Chloroquine',
    'Chlorphenamine',
    'Chlorpromazine',
    'Chlortalidone',
    'Cholecalciferol',
    'Cholestyramine',
    'Ciclosporin',
    'Cidofovir',
    'Cilastatin',
    'Cilazapril',
    'Cimetidine',
    'Cinchocaine',
    'Cinnarizine',
    'Ciprofloxacin',
    'Cisplatin',
    'Citalopram',
    'Cladribine',
    'Clarithromycin',
    'Clavulanic acid',
    'Clemastine',
    'Clindamycin',
    'Clobazam',
    'Clobetasol',
    'Clofazimine',
    'Clomifene',
    'Clomipramine',
    'Clonazepam',
    'Clonidine',
    'Clopidogrel',
    'Clotrimazole',
    'Clozapine',
    'Co-amoxiclav',
    'Co-codamol',
    'Co-dydramol',
    'Codeine',
    'Colchicine',
    'Colesevelam',
    'Colestipol',
    'Colistin',
    'Contraceptives (oral)',
    'Cortisone',
    'Crizotinib',
    'Cromoglicate',
    'Cyclizine',
    'Cyclophosphamide',
    'Cycloserine',
    'Cyclosporin',
    'Cyproheptadine',
    'Cytarabine',
    
    // D
    'Dabigatran',
    'Dabrafenib',
    'Dacarbazine',
    'Dactinomycin',
    'Dalbavancin',
    'Dalteparin',
    'Danazol',
    'Dantrolene',
    'Dapagliflozin',
    'Dapsone',
    'Daptomycin',
    'Darunavir',
    'Dasatinib',
    'Daunorubicin',
    'Deferasirox',
    'Deferiprone',
    'Deflazacort',
    'Delamanid',
    'Demeclocycline',
    'Denosumab',
    'Desflurane',
    'Desipramine',
    'Desloratadine',
    'Desmopressin',
    'Desogestrel',
    'Dexamethasone',
    'Dexlansoprazole',
    'Dextromethorphan',
    'Diazepam',
    'Diazoxide',
    'Diclofenac',
    'Dicycloverine',
    'Didanosine',
    'Diethylstilbestrol',
    'Digoxin',
    'Diltiazem',
    'Dimeticone',
    'Dinoprostone',
    'Diphenhydramine',
    'Diphenoxylate',
    'Diphtheria vaccine',
    'Dipyridamole',
    'Disopyramide',
    'Disulfiram',
    'Dobutamine',
    'Docetaxel',
    'Docusate',
    'Domperidone',
    'Donepezil',
    'Dopamine',
    'Dornase alfa',
    'Dorzolamide',
    'Doxazosin',
    'Doxepin',
    'Doxorubicin',
    'Doxycycline',
    'Dronedarone',
    'Droperidol',
    'Drospirenone',
    'Duloxetine',
    'Dutasteride',
    
    // E
    'Ebastine',
    'Eculizumab',
    'Edoxaban',
    'Efavirenz',
    'Eflornithine',
    'Eletriptan',
    'Eltrombopag',
    'Empagliflozin',
    'Enalapril',
    'Enfuvirtide',
    'Enoxaparin',
    'Entacapone',
    'Entecavir',
    'Enzalutamide',
    'Ephedrine',
    'Epinephrine',
    'Eplerenone',
    'Epoetin alfa',
    'Epoetin beta',
    'Eprosartan',
    'Eptifibatide',
    'Ergocalciferol',
    'Ergotamine',
    'Erlotinib',
    'Ertapenem',
    'Erythromycin',
    'Escitalopram',
    'Esmolol',
    'Esomeprazole',
    'Estradiol',
    'Estrogen',
    'Etanercept',
    'Ethambutol',
    'Ethinylestradiol',
    'Ethosuximide',
    'Etodolac',
    'Etoposide',
    'Etravirine',
    'Everolimus',
    'Exemestane',
    'Exenatide',
    'Ezetimibe',
    
    // F
    'Famciclovir',
    'Famotidine',
    'Febuxostat',
    'Felodipine',
    'Fenofibrate',
    'Fentanyl',
    'Ferrous fumarate',
    'Ferrous gluconate',
    'Ferrous sulfate',
    'Fesoterodine',
    'Fexofenadine',
    'Filgrastim',
    'Finasteride',
    'Flecainide',
    'Flucloxacillin',
    'Fluconazole',
    'Fludarabine',
    'Fludrocortisone',
    'Flumazenil',
    'Flunisolide',
    'Fluocinolone',
    'Fluocinonide',
    'Fluorometholone',
    'Fluorouracil',
    'Fluoxetine',
    'Flupentixol',
    'Fluphenazine',
    'Flurazepam',
    'Flurbiprofen',
    'Flutamide',
    'Fluticasone',
    'Fluvastatin',
    'Fluvoxamine',
    'Folic acid',
    'Follitropin',
    'Formoterol',
    'Fosamprenavir',
    'Foscarnet',
    'Fosfomycin',
    'Fosphenytoin',
    'Frovatriptan',
    'Furosemide',
    'Fusidic acid',
    
    // G
    'Gabapentin',
    'Galantamine',
    'Ganciclovir',
    'Gefitinib',
    'Gemcitabine',
    'Gemfibrozil',
    'Gentamicin',
    'Glibenclamide',
    'Gliclazide',
    'Glimepiride',
    'Glipizide',
    'Glucagon',
    'Glyburide',
    'Glycerol',
    'Glyceryl trinitrate',
    'Golimumab',
    'Goserelin',
    'Granisetron',
    'Griseofulvin',
    'Guanfacine',
    
    // H
    'Haloperidol',
    'Halothane',
    'Heparin',
    'Hepatitis B vaccine',
    'Hib vaccine',
    'Histamine',
    'Homatropine',
    'Hormonal therapy',
    'Human papillomavirus (HPV) vaccine',
    'Hydralazine',
    'Hydrochlorothiazide',
    'Hydrocodone',
    'Hydrocortisone',
    'Hydroflumethiazide',
    'Hydromorphone',
    'Hydroxocobalamin',
    'Hydroxychloroquine',
    'Hydroxyurea',
    'Hyoscine',
    'Hyoscyamine',
    
    // I
    'Ibandronate',
    'Ibuprofen',
    'Icatibant',
    'Idarubicin',
    'Ifosfamide',
    'Iloprost',
    'Imatinib',
    'Imidapril',
    'Imipenem',
    'Imipramine',
    'Immune globulin',
    'Indacaterol',
    'Indapamide',
    'Indinavir',
    'Indometacin',
    'Infliximab',
    'Influenza vaccine',
    'Insulin',
    'Interferon alfa',
    'Interferon beta',
    'Ipratropium',
    'Irbesartan',
    'Irinotecan',
    'Iron supplements',
    'Isavuconazole',
    'Isoniazid',
    'Isosorbide dinitrate',
    'Isosorbide mononitrate',
    'Isotretinoin',
    'Itraconazole',
    'Ivabradine',
    'Ivacaftor',
    'Ivermectin',
    'Ixazomib',
    
    // K
    'Kanamycin',
    'Ketamine',
    'Ketoconazole',
    'Ketoprofen',
    'Ketorolac',
    'Ketotifen',
    
    // L
    'Labetalol',
    'Lacosamide',
    'Lactulose',
    'Lamivudine',
    'Lamotrigine',
    'Lansoprazole',
    'Lapatinib',
    'Latanoprost',
    'Leflunomide',
    'Lenalidomide',
    'Lercanidipine',
    'Letrozole',
    'Leucovorin',
    'Leuprorelin',
    'Levalbuterol',
    'Levetiracetam',
    'Levocetirizine',
    'Levodopa',
    'Levofloxacin',
    'Levomepromazine',
    'Levonorgestrel',
    'Levothyroxine',
    'Lidocaine',
    'Linagliptin',
    'Linezolid',
    'Liraglutide',
    'Lisinopril',
    'Lithium',
    'Lofexidine',
    'Lomefloxacin',
    'Lomustine',
    'Loperamide',
    'Lopinavir',
    'Loratadine',
    'Lorazepam',
    'Losartan',
    'Lovastatin',
    'Loxapine',
    'Lubiprostone',
    'Lurasidone',
    
    // M
    'Macitentan',
    'Magnesium',
    'Malathion',
    'Mannitol',
    'Maprotiline',
    'Maraviroc',
    'Mebendazole',
    'Mebeverine',
    'Mecobalamin',
    'Medroxyprogesterone',
    'Mefenamic acid',
    'Mefloquine',
    'Megestrol',
    'Melatonin',
    'Meloxicam',
    'Melphalan',
    'Memantine',
    'MenACWY vaccine',
    'MenB vaccine',
    'Meningococcal vaccine',
    'Meprobamate',
    'Mercaptopurine',
    'Meropenem',
    'Mesalazine',
    'Mesna',
    'Metformin',
    'Methadone',
    'Methimazole',
    'Methocarbamol',
    'Methotrexate',
    'Methyldopa',
    'Methylphenidate',
    'Methylprednisolone',
    'Metoclopramide',
    'Metolazone',
    'Metoprolol',
    'Metronidazole',
    'Mianserin',
    'Miconazole',
    'Midazolam',
    'Mifepristone',
    'Miglitol',
    'Milnacipran',
    'Minocycline',
    'Minoxidil',
    'Mirabegron',
    'Mirtazapine',
    'Misoprostol',
    'Mitomycin',
    'Mitotane',
    'Mitoxantrone',
    'Moclobemide',
    'Modafinil',
    'Mometasone',
    'Montelukast',
    'Morphine',
    'Moxifloxacin',
    'Moxonidine',
    'Multivitamins',
    'Mupirocin',
    'Mycophenolate',
    
    // N
    'Nabumetone',
    'Nadolol',
    'Naloxone',
    'Naltrexone',
    'Naproxen',
    'Naratriptan',
    'Natalizumab',
    'Nateglinide',
    'Nebivolol',
    'Nedocromil',
    'Nefazodone',
    'Nelfinavir',
    'Neomycin',
    'Neostigmine',
    'Neratinib',
    'Nesiritide',
    'Netilmicin',
    'Nevirapine',
    'Niacin',
    'Nicardipine',
    'Nicotine',
    'Nifedipine',
    'Nilotinib',
    'Nimodipine',
    'Nimorazole',
    'Nintedanib',
    'Nitrazepam',
    'Nitrofurantoin',
    'Nizatidine',
    'Noradrenaline',
    'Norepinephrine',
    'Norethisterone',
    'Norfloxacin',
    'Nortriptyline',
    'Nystatin',
    
    // O
    'Obeticholic acid',
    'Octreotide',
    'Ofloxacin',
    'Olanzapine',
    'Olaparib',
    'Olmesartan',
    'Olodaterol',
    'Olsalazine',
    'Omeprazole',
    'Ondansetron',
    'Orlistat',
    'Orphenadrine',
    'Oseltamivir',
    'Oxaliplatin',
    'Oxazepam',
    'Oxcarbazepine',
    'Oxybutynin',
    'Oxycodone',
    'Oxymetazoline',
    'Oxytetracycline',
    'Oxytocin',
    
    // P
    'Paclitaxel',
    'Palbociclib',
    'Paliperidone',
    'Palivizumab',
    'Palonosetron',
    'Pamidronate',
    'Pancreatin',
    'Panitumumab',
    'Pantoprazole',
    'Papaverine',
    'Paracetamol',
    'Paroxetine',
    'Pazopanib',
    'Pegaspargase',
    'Peginterferon',
    'Pegloticase',
    'Pembrolizumab',
    'Penicillamine',
    'Penicillin',
    'Pentamidine',
    'Pentazocine',
    'Pentoxifylline',
    'Perampanel',
    'Perindopril',
    'Permethrin',
    'Perphenazine',
    'Pertuzumab',
    'Phenazopyridine',
    'Phenelzine',
    'Phenobarbital',
    'Phenoxymethylpenicillin',
    'Phentermine',
    'Phenytoin',
    'Physostigmine',
    'Pilocarpine',
    'Pimecrolimus',
    'Pimozide',
    'Pindolol',
    'Pioglitazone',
    'Piperacillin',
    'Pirfenidone',
    'Piroxicam',
    'Pitavastatin',
    'Pizotifen',
    'Pneumococcal vaccine',
    'Polio vaccine',
    'Polyethylene glycol',
    'Polymyxin B',
    'Pomalidomide',
    'Ponatinib',
    'Posaconazole',
    'Potassium',
    'Pramipexole',
    'Pramlintide',
    'Prasugrel',
    'Pravastatin',
    'Praziquantel',
    'Prazosin',
    'Prednisolone',
    'Prednisone',
    'Pregabalin',
    'Primaquine',
    'Primidone',
    'Probenecid',
    'Probiotics',
    'Procainamide',
    'Procarbazine',
    'Prochlorperazine',
    'Progesterone',
    'Proguanil',
    'Promethazine',
    'Propafenone',
    'Propantheline',
    'Propranolol',
    'Propofol',
    'Propylthiouracil',
    'Protamine',
    'Proton pump inhibitors',
    'Prucalopride',
    'Pseudoephedrine',
    'Psyllium',
    'Pyrazinamide',
    'Pyridostigmine',
    'Pyridoxine',
    'Pyrimethamine',
    
    // Q
    'Quetiapine',
    'Quinapril',
    'Quinidine',
    'Quinine',
    'Quinupristin',
    
    // R
    'Rabeprazole',
    'Rabies vaccine',
    'Raloxifene',
    'Raltegravir',
    'Ramipril',
    'Ranibizumab',
    'Ranitidine',
    'Rasagiline',
    'Rasburicase',
    'Reboxetine',
    'Regorafenib',
    'Remifentanil',
    'Repaglinide',
    'Retapamulin',
    'Ribavirin',
    'Rifabutin',
    'Rifampicin',
    'Rifapentine',
    'Rifaximin',
    'Rilpivirine',
    'Riluzole',
    'Rimantadine',
    'Risedronate',
    'Risperidone',
    'Ritonavir',
    'Rituximab',
    'Rivaroxaban',
    'Rivastigmine',
    'Rizatriptan',
    'Rocuronium',
    'Roflumilast',
    'Romidepsin',
    'Ropinirole',
    'Rosiglitazone',
    'Rosuvastatin',
    'Rotavirus vaccine',
    'Roxithromycin',
    'Rufinamide',
    'Ruxolitinib',
    
    // S
    'Salbutamol',
    'Salicylic acid',
    'Salmeterol',
    'Saquinavir',
    'Saxagliptin',
    'Scopolamine',
    'Secukinumab',
    'Selegiline',
    'Selenium',
    'Sertraline',
    'Sevelamer',
    'Sildenafil',
    'Silodosin',
    'Simvastatin',
    'Sirolimus',
    'Sitagliptin',
    'Sodium bicarbonate',
    'Sodium chloride',
    'Sodium valproate',
    'Solifenacin',
    'Somatropin',
    'Sorafenib',
    'Sotalol',
    'Spironolactone',
    'Statins',
    'Stavudine',
    'Streptokinase',
    'Streptomycin',
    'Succinylcholine',
    'Sucralfate',
    'Sulfadiazine',
    'Sulfamethoxazole',
    'Sulfasalazine',
    'Sulindac',
    'Sulpiride',
    'Sumatriptan',
    'Sunitinib',
    'Suxamethonium',
    
    // T
    'Tacrolimus',
    'Tadalafil',
    'Tamoxifen',
    'Tamsulosin',
    'Tapentadol',
    'Tazobactam',
    'Tegafur',
    'Telaprevir',
    'Telbivudine',
    'Telithromycin',
    'Telmisartan',
    'Temazepam',
    'Temozolomide',
    'Temsirolimus',
    'Tenecteplase',
    'Tenofovir',
    'Tepotinib',
    'Terazosin',
    'Terbinafine',
    'Terbutaline',
    'Terfenadine',
    'Teriparatide',
    'Testosterone',
    'Tetrabenazine',
    'Tetracycline',
    'Theophylline',
    'Thiamine',
    'Thiopental',
    'Thioridazine',
    'Thiotepa',
    'Thyroid medications',
    'Tiagabine',
    'Ticagrelor',
    'Ticarcillin',
    'Tigecycline',
    'Timolol',
    'Tinidazole',
    'Tioconazole',
    'Tiotropium',
    'Tipranavir',
    'Tirofiban',
    'Tizanidine',
    'Tobramycin',
    'Tocilizumab',
    'Tofacitinib',
    'Tolbutamide',
    'Tolcapone',
    'Tolterodine',
    'Topiramate',
    'Topotecan',
    'Torasemide',
    'Toremifene',
    'Torsemide',
    'Tramadol',
    'Trandolapril',
    'Tranexamic acid',
    'Trazodone',
    'Treprostinil',
    'Tretinoin',
    'Triamcinolone',
    'Triamterene',
    'Triazolam',
    'Trichlormethiazide',
    'Triclabendazole',
    'Triclosan',
    'Trifluoperazine',
    'Trimethoprim',
    'Trimipramine',
    'Triptorelin',
    'Tropicamide',
    'Trospium',
    'Typhoid vaccine',
    
    // U
    'Ulipristal',
    'Unoprostone',
    'Ursodeoxycholic acid',
    'Ustekinumab',
    
    // V
    'Valaciclovir',
    'Valganciclovir',
    'Valproic acid',
    'Valsartan',
    'Vancomycin',
    'Vandetanib',
    'Vardenafil',
    'Varenicline',
    'Varicella vaccine',
    'Vedolizumab',
    'Venlafaxine',
    'Verapamil',
    'Vigabatrin',
    'Vilazodone',
    'Vinblastine',
    'Vincristine',
    'Vinorelbine',
    'Vitamin A',
    'Vitamin B1',
    'Vitamin B12',
    'Vitamin B2',
    'Vitamin B3',
    'Vitamin B5',
    'Vitamin B6',
    'Vitamin B7',
    'Vitamin B9',
    'Vitamin C',
    'Vitamin D',
    'Vitamin E',
    'Vitamin K',
    'Voriconazole',
    'Vorinostat',
    'Vortioxetine',
    
    // W
    'Warfarin',
    
    // X
    'Xylometazoline',
    
    // Y
    'Yellow fever vaccine',
    
    // Z
    'Zafirlukast',
    'Zaleplon',
    'Zanamivir',
    'Zidovudine',
    'Zileuton',
    'Ziprasidone',
    'Zoledronic acid',
    'Zolmitriptan',
    'Zolpidem',
    'Zonisamide',
    'Zopiclone',
    'Zotepine',
    'Zuclopenthixol',
];
